name: PRs to feature
on: 
  pull_request:
    branches: [bugfix]
    types: [closed]
jobs:
  merge-master-back-to-dev:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "saikumarg1324@gmail.com"
          git config --local user.name "saikumarg13249"
          git config pull.ff only
    - name: Merge bugfix to feature
      run: |
        git fetch origin
        git branch
        git checkout origin/dev
        git pull origin bugfix --allow-unrelated-histories
        git merge origin/bugfix
#check
